Main.JPanel.0.class=com.cccint.test.testtool.gui.JPanelBoard
Main.JPanel.1.class=com.cccint.test.testtool.gui.JPanelClient
Main.JPanel.2.class=com.cccint.test.testtool.gui.JPanelServer
Main.JPanel.3.class=com.cccint.test.testtool.gui.JPanelDesigna
Main.JPanel.4.class=com.cccint.test.testtool.gui.JPanelDccCheck
Main.JPanel.5.class=com.cccint.test.testtool.gui.JPanelDccServer
Main.JPanel.6.class=com.cccint.test.testtool.gui.JPanel3cXml
Main.JPanel.7.class=com.cccint.test.testtool.gui.JPanel9000
Main.JPanel.8.class=com.cccint.test.testtool.gui.JPanelPayAtTable
Main.JPanel.9.class=com.cccint.test.testtool.gui.JPanelPayAtTableSIXml
Main.JPanel.10.class=com.cccint.test.testtool.gui.JPanelPayAtTableOPI
Main.JPanel.11.class=com.cccint.test.testtool.gui.JPanelPayAtTableSTSGen2
Main.JPanel.12.class=com.cccint.test.testtool.gui.JPanelMp1CardTable
Main.JPanel.13.class=com.cccint.test.testtool.gui.JPanelScs
Main.JPanel.14.class=com.cccint.test.testtool.gui.JPanelTmsServer
Main.JPanel.15.class=com.cccint.test.testtool.gui.JPanelTfsClient
Main.JPanel.16.class=com.cccint.test.testtool.gui.JPanelTerminalConfig
Main.JPanel.17.class=com.cccint.test.testtool.gui.JPanelLogServerJSon
Main.JPanel.18.class=com.cccint.test.testtool.gui.JPanelZippin
Main.JPanel.19.class=JPanelKeyEncryption